### ISSUE TITLE
Cannot build Phantom on macOS

### ISSUE THREAD

**Issue by dmentipl** [danieljprice/phantom#65]
I cannot build Phantom on macOS (10.15.6).

gfortran version: 10.2.0 installed via Homebrew

I try with:

```
make SETUP=empty SYSTEM=gfortran
```

It fails with:

```
gfortran -O3 -Wall -Wno-unused-dummy-argument -frecord-marker=4 -gdwarf-2 -finline-functions-called-once -finline-limit=1500 -funroll-loops -ftree-vectorize -std=f2008 -fall-intrinsics -fPIC -fopenmp -fdefault-real-8 -fdefault-double-8 -o ../bin/phantom physcon.o config.o kernel_cubic.o io.o units.o boundary.o mpi_utils.o dtype_kdtree.o utils_omp.o utils_cpuinfo.o utils_allocate.o icosahedron.o utils_mathfunc.o part.o mpi_domain.o utils_timing.o mpi_balance.o setup_params.o timestep.o utils_dumpfiles.o utils_indtimesteps.o utils_infiles.o utils_sort.o utils_supertimestep.o utils_tables.o utils_gravwave.o utils_sphNG.o utils_vectors.o utils_datafiles.o datafiles.o gitinfo.o random.o eos_mesa_microphysics.o eos_mesa.o eos_shen.o eos_helmholtz.o eos_idealplusrad.o eos.o cullendehnen.o nicil.o nicil_supplement.o inverse4x4.o metric_minkowski.o metric_tools.o utils_gr.o cons2primsolver.o checkoptions.o viscosity.o options.o radiation_utils.o cons2prim.o centreofmass.o extern_corotate.o extern_binary.o extern_spiral.o extern_lensethirring.o extern_gnewton.o lumin_nsdisc.o extern_prdrag.o extern_Bfield.o extern_densprofile.o extern_staticsine.o extern_gwinspiral.o externalforces.o damping.o checkconserved.o partinject.o utils_inject.o utils_filenames.o utils_summary.o fs_data.o mol_data.o utils_spline.o h2cooling.o h2chem.o cooling.o dust.o growth.o dust_formation.o ptmass_radiation.o mpi_dens.o mpi_force.o stack.o mpi_derivs.o kdtree.o linklist_kdtree.o memory.o readwrite_dumps_common.o readwrite_dumps_fortran.o readwrite_dumps.o quitdump.o ptmass.o readwrite_infile.o dens.o force.o utils_deriv.o deriv.o energies.o sort_particles.o evwrite.o step_leapfrog.o writeheader.o step_supertimestep.o mf_write.o evolve.o checksetup.o initial.o phantom.o
Undefined symbols for architecture x86_64:
  "_GOMP_loop_maybe_nonmonotonic_runtime_next", referenced from:
      ___timestep_sts_MOD_sts_init_step._omp_fn.0 in utils_supertimestep.o
      ___densityforce_MOD_densityiterate._omp_fn.0 in dens.o
      ___forces_MOD_force._omp_fn.0 in force.o
  "_GOMP_loop_maybe_nonmonotonic_runtime_start", referenced from:
      ___timestep_sts_MOD_sts_init_step._omp_fn.0 in utils_supertimestep.o
      ___densityforce_MOD_densityiterate._omp_fn.0 in dens.o
      ___forces_MOD_force._omp_fn.0 in force.o
  "__gfortran_os_error_at", referenced from:
      ___dump_utils_MOD_read_array_real8arr in utils_dumpfiles.o
      ___dump_utils_MOD_read_array_real8 in utils_dumpfiles.o
      ___table_utils_MOD_diff in utils_tables.o
      ___table_utils_MOD_flip_array in utils_tables.o
      ___mesa_microphysics_MOD_get_eos_constants_mesa in eos_mesa_microphysics.o
      ___mesa_microphysics_MOD_read_opacity_mesa in eos_mesa_microphysics.o
      ___mesa_microphysics_MOD_get_opacity_constants_mesa in eos_mesa_microphysics.o
      ...
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[1]: *** [phantom] Error 1
make: *** [phantom] Error 2
```

**Comment by bjnorfolk** [comment]
I'm on identical versions for macOS and gfortran, getting the same errors. The ```make test``` also fails with:
```
--> testing sink particle creation (sin)
 >>>>>>  s  t  r  e   t    c     h       m     a    p   p  i  n  g  <<<<<<
 stretching to match density profile in r direction
 density at r =    0.0000000000000000       is    1.0000000000000000     
 total mass      =    6.9604063530626938E-004

Program received signal SIGBUS: Access to an undefined portion of a memory object.

Program received signal SIGBUS: Access to an undefined portion of a memory object.

Backtrace for this error:

Program received signal SIGBUS: Access to an undefined portion of a memory object.

Backtrace for this error:

Backtrace for this error:
/bin/bash: line 1: 90055 Segmentation fault: 11  ../bin/phantomtest
make[1]: *** [test] Error 139
make: *** [test] Error 2
```

**Comment by bjnorfolk** [comment]
But all appears to work on my linux machine? Which is also using gfortran?

**Comment by jameswurster** [comment]
Everything works fine on my Mac, version 10.14.6 using GNU Fortran (Homebrew GCC 9.3.0_1) 9.3.0.

In addition to checking your library links (as Daniel previously mentioned), have you looked into the compiling errors or to see if there have been any changes to the compiler flags?

**Comment by dmentipl** [comment]
Hi @jameswurster, thanks for your suggestions. There's no library linking flags as this is pure Phantom, no HDF5.

I've actually discovered the issue. It's my conda installation. The conda installed ld binary is ahead on the path.

```bash
$ which -a ld
/Users/daniel/conda/bin/ld
/usr/bin/ld
```

Deactivating conda with `conda deactivate` which removes the conda ld binary from the path fixed the issue.

@bjnorfolk: can you please test this too?

**Comment by danieljprice** [comment]
@bjnorfolk, the problem is that you have conflicting versions of gfortran on your Mac. You are linking against a version of libgfortran (via your -L flags) that is different to the one used to compile phantom.

**Comment by danieljprice** [comment]
there is also a bug in gfortran v10.2.0 causing the seg fault (#59)

**Comment by dmentipl** [comment]
I'm happy that this has been resolved, i.e. it wasn't a bug, just issues with the ld binary due to my PATH variable (and I assume @bjnorfolk's too).
